### ISSUE TITLE
Save/Load/resume training?

### ISSUE THREAD

**Issue by jheffez** [germain-hug/Deep-RL-Keras#10]
Hello and thanks for sharing your code! 
Can you please let me know if there is a way to save model state/weights in order to test later or resume training?

**Comment by germain-hug** [comment]
Hi and thanks for your interest!
I just modified ```main.py``` to save weights when done training. I also added a separate script (```load_and_run.py```) for visualization after training.

**Comment by jheffez** [comment]
Great! I'll give it a shot
