### ISSUE TITLE
Testing A3C

### ISSUE THREAD

**Issue by ndeshp2s** [germain-hug/Deep-RL-Keras#13]
I tried testing the trained model on A3C on CartPole-v1 environment. However, I get the following error:
"ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (4, 4)"

**Comment by thaume** [comment]
Hi @ndeshp2s, try changing the code in `A3C/agent.py` as follows :
```
# line 25, in reshape()
return np.expand_dims(x, axis=0)
```
It should work fine for CartPole-v1 after that ;)
