### ISSUE TITLE
[Error] Fetch data for Adam

### ISSUE THREAD

**Issue by moakra** [germain-hug/Deep-RL-Keras#3]
Hi,

When I try to run the ddpg code as follows:

`python3 main.py --type DDPG --env LunarLanderContinuous-v2`

an error happens in Deep-RL-Keras/DDPG/actor.py at line 63, in the train function
                             self.adam_optimizer([states, grads]):

`File "./.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1441, in __init__
    session._session, options_ptr, status)
  File "./.venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to fetch data for 'Adam', which produces no output.  To run to a node but not fetch any data, pass 'Adam' as an argument to the 'target_node_names' argument of the Session::Run API.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f830c0528d0>>
Traceback (most recent call last):
  File "./.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1467, in __del__
    self._session._session, self._handle, status)
  File "./.venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No such callable handle: 140198369660512`

Did you already have this issue ?

**Comment by germain-hug** [comment]
Hi,
I don’t recall encountering this error, have you checked that you are using Keras 2.1.6 ?

**Comment by moakra** [comment]
I downgraded Keras and now it works. Weird.
Thank you!
